require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/game_trainings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # GameTraining. As you add validations to GameTraining, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      GameTraining.create! valid_attributes
      get game_trainings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      game_training = GameTraining.create! valid_attributes
      get game_training_url(game_training)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_game_training_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      game_training = GameTraining.create! valid_attributes
      get edit_game_training_url(game_training)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GameTraining" do
        expect {
          post game_trainings_url, params: { game_training: valid_attributes }
        }.to change(GameTraining, :count).by(1)
      end

      it "redirects to the created game_training" do
        post game_trainings_url, params: { game_training: valid_attributes }
        expect(response).to redirect_to(game_training_url(GameTraining.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GameTraining" do
        expect {
          post game_trainings_url, params: { game_training: invalid_attributes }
        }.to change(GameTraining, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post game_trainings_url, params: { game_training: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested game_training" do
        game_training = GameTraining.create! valid_attributes
        patch game_training_url(game_training), params: { game_training: new_attributes }
        game_training.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the game_training" do
        game_training = GameTraining.create! valid_attributes
        patch game_training_url(game_training), params: { game_training: new_attributes }
        game_training.reload
        expect(response).to redirect_to(game_training_url(game_training))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        game_training = GameTraining.create! valid_attributes
        patch game_training_url(game_training), params: { game_training: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested game_training" do
      game_training = GameTraining.create! valid_attributes
      expect {
        delete game_training_url(game_training)
      }.to change(GameTraining, :count).by(-1)
    end

    it "redirects to the game_trainings list" do
      game_training = GameTraining.create! valid_attributes
      delete game_training_url(game_training)
      expect(response).to redirect_to(game_trainings_url)
    end
  end
end
